; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = main

[common]
platform      = espressif32
board         = esp32-s3-devkitc-1
framework     = arduino
board_build.f_cpu = 240000000L
extra_scripts = post:tools/notify_upload.py
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
flash_speed   = 80000000L
lib_deps =
    h2zero/NimBLE-Arduino@^2.5.0
    olikraus/U8g2@^2.35.30

[env:main]
extends = common
build_src_filter = +<main.cpp>

[env:sensor-cal]
extends = common
build_src_filter = +<../test/sensor_cal.cpp>

[env:sensor-cal-ble]
extends = common
build_src_filter = +<../test/sensor-cal-ble.cpp>

[env:motor-ble]
extends = common
build_src_filter = +<../test/motor-ble-drive.cpp>

[env:encoder-test]
extends = common
build_src_filter = +<../test/encoder-test.cpp>

[env:ir-test]
extends = common
build_src_filter = +<../test/ir-test.cpp>

[env:wall-follow]
extends = common
build_src_filter = +<../test/wall-follow-simple.cpp>

[env:wall-follow-cells]
extends = common
build_src_filter = +<../test/wall-follow-encoder-count-cell.cpp>

[env:imu-turn]
extends = common
build_src_filter = +<../test/mpu6500.cpp>

[env:side-open-turn]
extends = common
build_src_filter = +<../test/side-open-turn.cpp>

[env:motor-freq]
extends = common
build_src_filter = +<../test/motor-freq-config.cpp>

[env:velocity-pid]
extends = common
build_src_filter = +<../test/velocity-pid.cpp>

[env:velocity-pid-ble]
extends = common
build_src_filter = +<../test/velocity-pid-ble.cpp>



